
package org.occ.p3.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "userWs", targetNamespace = "http://serviceWeb.p3.occ.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserWs {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "init", targetNamespace = "http://serviceWeb.p3.occ.org/", className = "org.occ.p3.serviceweb.Init")
    @ResponseWrapper(localName = "initResponse", targetNamespace = "http://serviceWeb.p3.occ.org/", className = "org.occ.p3.serviceweb.InitResponse")
    @Action(input = "http://serviceWeb.p3.occ.org/userWs/initRequest", output = "http://serviceWeb.p3.occ.org/userWs/initResponse")
    public void init();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns org.occ.p3.serviceweb.Member
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByUserNameAndPassword", targetNamespace = "http://serviceWeb.p3.occ.org/", className = "org.occ.p3.serviceweb.FindByUserNameAndPassword")
    @ResponseWrapper(localName = "findByUserNameAndPasswordResponse", targetNamespace = "http://serviceWeb.p3.occ.org/", className = "org.occ.p3.serviceweb.FindByUserNameAndPasswordResponse")
    @Action(input = "http://serviceWeb.p3.occ.org/userWs/findByUserNameAndPasswordRequest", output = "http://serviceWeb.p3.occ.org/userWs/findByUserNameAndPasswordResponse")
    public Member findByUserNameAndPassword(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isValidUser", targetNamespace = "http://serviceWeb.p3.occ.org/", className = "org.occ.p3.serviceweb.IsValidUser")
    @ResponseWrapper(localName = "isValidUserResponse", targetNamespace = "http://serviceWeb.p3.occ.org/", className = "org.occ.p3.serviceweb.IsValidUserResponse")
    @Action(input = "http://serviceWeb.p3.occ.org/userWs/isValidUserRequest", output = "http://serviceWeb.p3.occ.org/userWs/isValidUserResponse")
    public boolean isValidUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
