
package org.occ.p3.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "workWs", targetNamespace = "http://serviceWeb.p3.occ.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WorkWs {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "init", targetNamespace = "http://serviceWeb.p3.occ.org/", className = "org.occ.p3.serviceweb.Init")
    @ResponseWrapper(localName = "initResponse", targetNamespace = "http://serviceWeb.p3.occ.org/", className = "org.occ.p3.serviceweb.InitResponse")
    @Action(input = "http://serviceWeb.p3.occ.org/workWs/initRequest", output = "http://serviceWeb.p3.occ.org/workWs/initResponse")
    public void init();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<org.occ.p3.serviceweb.Work>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getWorksByPublicationDate", targetNamespace = "http://serviceWeb.p3.occ.org/", className = "org.occ.p3.serviceweb.GetWorksByPublicationDate")
    @ResponseWrapper(localName = "getWorksByPublicationDateResponse", targetNamespace = "http://serviceWeb.p3.occ.org/", className = "org.occ.p3.serviceweb.GetWorksByPublicationDateResponse")
    @Action(input = "http://serviceWeb.p3.occ.org/workWs/getWorksByPublicationDateRequest", output = "http://serviceWeb.p3.occ.org/workWs/getWorksByPublicationDateResponse")
    public List<Work> getWorksByPublicationDate(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<org.occ.p3.serviceweb.Work>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getWorksByAuthor", targetNamespace = "http://serviceWeb.p3.occ.org/", className = "org.occ.p3.serviceweb.GetWorksByAuthor")
    @ResponseWrapper(localName = "getWorksByAuthorResponse", targetNamespace = "http://serviceWeb.p3.occ.org/", className = "org.occ.p3.serviceweb.GetWorksByAuthorResponse")
    @Action(input = "http://serviceWeb.p3.occ.org/workWs/getWorksByAuthorRequest", output = "http://serviceWeb.p3.occ.org/workWs/getWorksByAuthorResponse")
    public List<Work> getWorksByAuthor(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
