
package org.occ.bibliot.client.endpoint;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "userWs", targetNamespace = "http://user.serviceWeb.p3.occ.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserWs {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "init", targetNamespace = "http://user.serviceWeb.p3.occ.org/", className = "org.occ.p3.client.endpoint.Init")
    @ResponseWrapper(localName = "initResponse", targetNamespace = "http://user.serviceWeb.p3.occ.org/", className = "org.occ.p3.client.endpoint.InitResponse")
    @Action(input = "http://user.serviceWeb.p3.occ.org/userWs/initRequest", output = "http://user.serviceWeb.p3.occ.org/userWs/initResponse")
    public void init();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<org.occ.p3.client.endpoint.Borrow>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findBorrowListByMember", targetNamespace = "http://user.serviceWeb.p3.occ.org/", className = "org.occ.p3.client.endpoint.FindBorrowListByMember")
    @ResponseWrapper(localName = "findBorrowListByMemberResponse", targetNamespace = "http://user.serviceWeb.p3.occ.org/", className = "org.occ.p3.client.endpoint.FindBorrowListByMemberResponse")
    @Action(input = "http://user.serviceWeb.p3.occ.org/userWs/findBorrowListByMemberRequest", output = "http://user.serviceWeb.p3.occ.org/userWs/findBorrowListByMemberResponse")
    public List<Borrow> findBorrowListByMember(
        @WebParam(name = "arg0", targetNamespace = "")
        Member arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns org.occ.p3.client.endpoint.Member
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isValidUser", targetNamespace = "http://user.serviceWeb.p3.occ.org/", className = "org.occ.p3.client.endpoint.IsValidUser")
    @ResponseWrapper(localName = "isValidUserResponse", targetNamespace = "http://user.serviceWeb.p3.occ.org/", className = "org.occ.p3.client.endpoint.IsValidUserResponse")
    @Action(input = "http://user.serviceWeb.p3.occ.org/userWs/isValidUserRequest", output = "http://user.serviceWeb.p3.occ.org/userWs/isValidUserResponse")
    public Member isValidUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
