
package org.occ.p3.client.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "batchWs", targetNamespace = "http://batch.serviceWeb.p3.occ.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BatchWs {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "init", targetNamespace = "http://batch.serviceWeb.p3.occ.org/", className = "org.occ.p3.client.endpoint.Init")
    @ResponseWrapper(localName = "initResponse", targetNamespace = "http://batch.serviceWeb.p3.occ.org/", className = "org.occ.p3.client.endpoint.InitResponse")
    @Action(input = "http://batch.serviceWeb.p3.occ.org/batchWs/initRequest", output = "http://batch.serviceWeb.p3.occ.org/batchWs/initResponse")
    public void init();

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "sendMailToLateBorrowMember", targetNamespace = "http://batch.serviceWeb.p3.occ.org/", className = "org.occ.p3.client.endpoint.SendMailToLateBorrowMember")
    @ResponseWrapper(localName = "sendMailToLateBorrowMemberResponse", targetNamespace = "http://batch.serviceWeb.p3.occ.org/", className = "org.occ.p3.client.endpoint.SendMailToLateBorrowMemberResponse")
    @Action(input = "http://batch.serviceWeb.p3.occ.org/batchWs/sendMailToLateBorrowMemberRequest", output = "http://batch.serviceWeb.p3.occ.org/batchWs/sendMailToLateBorrowMemberResponse")
    public void sendMailToLateBorrowMember();

}
