
package org.occ.p3.client.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WorkWeb", targetNamespace = "http://webservice.p3.occ.org/", wsdlLocation = "http://localhost:8080/webservice/ws/wsWork?wsdl")
public class WorkWeb
    extends Service
{

    private final static URL WORKWEB_WSDL_LOCATION;
    private final static WebServiceException WORKWEB_EXCEPTION;
    private final static QName WORKWEB_QNAME = new QName("http://webservice.p3.occ.org/", "WorkWeb");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/webservice/ws/wsWork?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WORKWEB_WSDL_LOCATION = url;
        WORKWEB_EXCEPTION = e;
    }

    public WorkWeb() {
        super(__getWsdlLocation(), WORKWEB_QNAME);
    }

    public WorkWeb(WebServiceFeature... features) {
        super(__getWsdlLocation(), WORKWEB_QNAME, features);
    }

    public WorkWeb(URL wsdlLocation) {
        super(wsdlLocation, WORKWEB_QNAME);
    }

    public WorkWeb(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WORKWEB_QNAME, features);
    }

    public WorkWeb(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WorkWeb(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WsWork
     */
    @WebEndpoint(name = "WsWorkPort")
    public WsWork getWsWorkPort() {
        return super.getPort(new QName("http://webservice.p3.occ.org/", "WsWorkPort"), WsWork.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsWork
     */
    @WebEndpoint(name = "WsWorkPort")
    public WsWork getWsWorkPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.p3.occ.org/", "WsWorkPort"), WsWork.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WORKWEB_EXCEPTION!= null) {
            throw WORKWEB_EXCEPTION;
        }
        return WORKWEB_WSDL_LOCATION;
    }

}
