
package org.occ.p3.client.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WsBorrow", targetNamespace = "http://webservice.p3.occ.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsBorrow {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "init", targetNamespace = "http://webservice.p3.occ.org/", className = "org.occ.p3.client.ws.Init")
    @ResponseWrapper(localName = "initResponse", targetNamespace = "http://webservice.p3.occ.org/", className = "org.occ.p3.client.ws.InitResponse")
    @Action(input = "http://webservice.p3.occ.org/WsBorrow/initRequest", output = "http://webservice.p3.occ.org/WsBorrow/initResponse")
    public void init();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "borrowBook", targetNamespace = "http://webservice.p3.occ.org/", className = "org.occ.p3.client.ws.BorrowBook")
    @ResponseWrapper(localName = "borrowBookResponse", targetNamespace = "http://webservice.p3.occ.org/", className = "org.occ.p3.client.ws.BorrowBookResponse")
    @Action(input = "http://webservice.p3.occ.org/WsBorrow/borrowBookRequest", output = "http://webservice.p3.occ.org/WsBorrow/borrowBookResponse")
    public Boolean borrowBook(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Integer arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "endBorrow", targetNamespace = "http://webservice.p3.occ.org/", className = "org.occ.p3.client.ws.EndBorrow")
    @ResponseWrapper(localName = "endBorrowResponse", targetNamespace = "http://webservice.p3.occ.org/", className = "org.occ.p3.client.ws.EndBorrowResponse")
    @Action(input = "http://webservice.p3.occ.org/WsBorrow/endBorrowRequest", output = "http://webservice.p3.occ.org/WsBorrow/endBorrowResponse")
    public Boolean endBorrow(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "extendBorrow", targetNamespace = "http://webservice.p3.occ.org/", className = "org.occ.p3.client.ws.ExtendBorrow")
    @ResponseWrapper(localName = "extendBorrowResponse", targetNamespace = "http://webservice.p3.occ.org/", className = "org.occ.p3.client.ws.ExtendBorrowResponse")
    @Action(input = "http://webservice.p3.occ.org/WsBorrow/extendBorrowRequest", output = "http://webservice.p3.occ.org/WsBorrow/extendBorrowResponse")
    public Boolean extendBorrow(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @return
     *     returns java.util.List<org.occ.p3.client.ws.Borrow>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBorrowListWithEndDateExceeded", targetNamespace = "http://webservice.p3.occ.org/", className = "org.occ.p3.client.ws.GetBorrowListWithEndDateExceeded")
    @ResponseWrapper(localName = "getBorrowListWithEndDateExceededResponse", targetNamespace = "http://webservice.p3.occ.org/", className = "org.occ.p3.client.ws.GetBorrowListWithEndDateExceededResponse")
    @Action(input = "http://webservice.p3.occ.org/WsBorrow/getBorrowListWithEndDateExceededRequest", output = "http://webservice.p3.occ.org/WsBorrow/getBorrowListWithEndDateExceededResponse")
    public List<Borrow> getBorrowListWithEndDateExceeded();

}
