
package org.occ.p3.client.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WsBook", targetNamespace = "http://webservice.p3.occ.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsBook {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "init", targetNamespace = "http://webservice.p3.occ.org/", className = "org.occ.p3.client.ws.Init")
    @ResponseWrapper(localName = "initResponse", targetNamespace = "http://webservice.p3.occ.org/", className = "org.occ.p3.client.ws.InitResponse")
    @Action(input = "http://webservice.p3.occ.org/WsBook/initRequest", output = "http://webservice.p3.occ.org/WsBook/initResponse")
    public void init();

    /**
     * 
     * @param arg0
     * @return
     *     returns org.occ.p3.client.ws.Book
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBookById", targetNamespace = "http://webservice.p3.occ.org/", className = "org.occ.p3.client.ws.GetBookById")
    @ResponseWrapper(localName = "getBookByIdResponse", targetNamespace = "http://webservice.p3.occ.org/", className = "org.occ.p3.client.ws.GetBookByIdResponse")
    @Action(input = "http://webservice.p3.occ.org/WsBook/getBookByIdRequest", output = "http://webservice.p3.occ.org/WsBook/getBookByIdResponse")
    public Book getBookById(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns org.occ.p3.client.ws.Book
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveNewBook", targetNamespace = "http://webservice.p3.occ.org/", className = "org.occ.p3.client.ws.SaveNewBook")
    @ResponseWrapper(localName = "saveNewBookResponse", targetNamespace = "http://webservice.p3.occ.org/", className = "org.occ.p3.client.ws.SaveNewBookResponse")
    @Action(input = "http://webservice.p3.occ.org/WsBook/saveNewBookRequest", output = "http://webservice.p3.occ.org/WsBook/saveNewBookResponse")
    public Book saveNewBook(
        @WebParam(name = "arg0", targetNamespace = "")
        Book arg0);

}
