
package org.occ.p3.client.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WsUser", targetNamespace = "http://webservice.p3.occ.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsUser {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "init", targetNamespace = "http://webservice.p3.occ.org/", className = "org.occ.p3.client.ws.Init")
    @ResponseWrapper(localName = "initResponse", targetNamespace = "http://webservice.p3.occ.org/", className = "org.occ.p3.client.ws.InitResponse")
    @Action(input = "http://webservice.p3.occ.org/WsUser/initRequest", output = "http://webservice.p3.occ.org/WsUser/initResponse")
    public void init();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isValidUser", targetNamespace = "http://webservice.p3.occ.org/", className = "org.occ.p3.client.ws.IsValidUser")
    @ResponseWrapper(localName = "isValidUserResponse", targetNamespace = "http://webservice.p3.occ.org/", className = "org.occ.p3.client.ws.IsValidUserResponse")
    @Action(input = "http://webservice.p3.occ.org/WsUser/isValidUserRequest", output = "http://webservice.p3.occ.org/WsUser/isValidUserResponse")
    public boolean isValidUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns org.occ.p3.client.ws.Member
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByUserNameAndPassword", targetNamespace = "http://webservice.p3.occ.org/", className = "org.occ.p3.client.ws.FindByUserNameAndPassword")
    @ResponseWrapper(localName = "findByUserNameAndPasswordResponse", targetNamespace = "http://webservice.p3.occ.org/", className = "org.occ.p3.client.ws.FindByUserNameAndPasswordResponse")
    @Action(input = "http://webservice.p3.occ.org/WsUser/findByUserNameAndPasswordRequest", output = "http://webservice.p3.occ.org/WsUser/findByUserNameAndPasswordResponse")
    public Member findByUserNameAndPassword(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
