
package org.occ.p3.client.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WsWork", targetNamespace = "http://webservice.p3.occ.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsWork {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "init", targetNamespace = "http://webservice.p3.occ.org/", className = "org.occ.p3.client.ws.Init")
    @ResponseWrapper(localName = "initResponse", targetNamespace = "http://webservice.p3.occ.org/", className = "org.occ.p3.client.ws.InitResponse")
    @Action(input = "http://webservice.p3.occ.org/WsWork/initRequest", output = "http://webservice.p3.occ.org/WsWork/initResponse")
    public void init();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<org.occ.p3.client.ws.Work>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getWorksByAuthor", targetNamespace = "http://webservice.p3.occ.org/", className = "org.occ.p3.client.ws.GetWorksByAuthor")
    @ResponseWrapper(localName = "getWorksByAuthorResponse", targetNamespace = "http://webservice.p3.occ.org/", className = "org.occ.p3.client.ws.GetWorksByAuthorResponse")
    @Action(input = "http://webservice.p3.occ.org/WsWork/getWorksByAuthorRequest", output = "http://webservice.p3.occ.org/WsWork/getWorksByAuthorResponse")
    public List<Work> getWorksByAuthor(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<org.occ.p3.client.ws.Work>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getWorksByPublicationDate", targetNamespace = "http://webservice.p3.occ.org/", className = "org.occ.p3.client.ws.GetWorksByPublicationDate")
    @ResponseWrapper(localName = "getWorksByPublicationDateResponse", targetNamespace = "http://webservice.p3.occ.org/", className = "org.occ.p3.client.ws.GetWorksByPublicationDateResponse")
    @Action(input = "http://webservice.p3.occ.org/WsWork/getWorksByPublicationDateRequest", output = "http://webservice.p3.occ.org/WsWork/getWorksByPublicationDateResponse")
    public List<Work> getWorksByPublicationDate(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

}
