
package org.occ.p3.serviceweb.batch;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "batchWeb", targetNamespace = "http://batch.serviceWeb.p3.occ.org/", wsdlLocation = "http://localhost:8080/serviceWeb/ws/batchresult/batchWs?wsdl")
public class BatchWeb
    extends Service
{

    private final static URL BATCHWEB_WSDL_LOCATION;
    private final static WebServiceException BATCHWEB_EXCEPTION;
    private final static QName BATCHWEB_QNAME = new QName("http://batch.serviceWeb.p3.occ.org/", "batchWeb");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/serviceWeb/ws/batchresult/batchWs?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BATCHWEB_WSDL_LOCATION = url;
        BATCHWEB_EXCEPTION = e;
    }

    public BatchWeb() {
        super(__getWsdlLocation(), BATCHWEB_QNAME);
    }

    public BatchWeb(WebServiceFeature... features) {
        super(__getWsdlLocation(), BATCHWEB_QNAME, features);
    }

    public BatchWeb(URL wsdlLocation) {
        super(wsdlLocation, BATCHWEB_QNAME);
    }

    public BatchWeb(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BATCHWEB_QNAME, features);
    }

    public BatchWeb(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BatchWeb(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BatchWs
     */
    @WebEndpoint(name = "batchWsPort")
    public BatchWs getBatchWsPort() {
        return super.getPort(new QName("http://batch.serviceWeb.p3.occ.org/", "batchWsPort"), BatchWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BatchWs
     */
    @WebEndpoint(name = "batchWsPort")
    public BatchWs getBatchWsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://batch.serviceWeb.p3.occ.org/", "batchWsPort"), BatchWs.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BATCHWEB_EXCEPTION!= null) {
            throw BATCHWEB_EXCEPTION;
        }
        return BATCHWEB_WSDL_LOCATION;
    }

}
